### ISSUE TITLE
unable to run command line inspection

### ISSUE THREAD

**Issue by ccjon** [googleapis/nodejs-dlp#241]
Following documents @ google here:
https://cloud.google.com/dlp/docs/quickstart-cli

#### Environment details

  - OS: official node:8 docker image
  - Node.js version: v8.15.0
  - npm version: 6.4.1
  - `@google-cloud/dlp` version: v0.10.0

#### Steps to reproduce

  1. docker run -it node:8 bash
  2. cd && git clone https://github.com/googleapis/nodejs-dlp && cd nodejs-dlp
  3. git checkout v0.10.0
  4. npm install
  5. node samples/inspect.js string "555555555"
  6. cd samples && node inspect.js string "555555555"

results for#5 or #6:
/root/nodejs-dlp/samples/inspect.js:797
  .recommendCommands()
   ^

TypeError: require(...).demand(...).command(...).command(...).command(...).command(...).command(...).option(...).option(...).option(...).option(...).option(...).option(...).option(...).option(...).option(...).example(...).example(...).example(...).example(...).example(...).wrap(...).recommendCommands is not a function
    at Object.<anonymous> (/root/nodejs-dlp/samples/inspect.js:797:4)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

**Comment by jkwlui** [comment]
In Step 4., you'd need to change to the `./samples` directory *and then* run `npm install`:

```
cd ./samples
npm install
```

Sorry for the confusion on the instructions. I've made a (pending) change to that page to make the instructions more clear.
