### ISSUE TITLE
Supplying Credentials Bug: Header field "authorization" must only have a single value

### ISSUE THREAD

**Issue by DanielSwiegersServian** [googleapis/nodejs-dlp#297]
Please run down the following list and make sure you've tried the usual "quick fixes":

  ✔ Search the issues already opened: https://github.com/googleapis/nodejs-dlp/issues
  ✔ Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  ✔ Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: `OSX High Serria`
  - Node.js version: `v10.11.0`
  - npm version: `6.4.1`
  - `@google-cloud/dlp` version: `1.1.0`

#### Steps to reproduce

1. Using sample https://github.com/googleapis/nodejs-dlp/blob/master/samples/redact.js
Supply service account credentials by replacing the following line in the sample 
```
const dlp = new DLP.DlpServiceClient();
```
 with
```
const dlp = new DLP.DlpServiceClient({
  projectId: serviceAccountJson.project_id,
  credentials: serviceAccountJson,
});
```

Calls such as: 
`dlp.listInfoTypes({})`
`dlp.projectPath('my-project')`
work as expected with the service account

Calls such as: `dlp.deidentifyContent` break with the following error:

```
UnhandledPromiseRejectionWarning: Error: Getting metadata from plugin failed with error: Header field "authorization" must only have a single value
    at Http2CallStream.call.on (/Users/MY_PROJECT_PATH/node_modules/@grpc/grpc-js/build/src/client.js:101:45)
    at Http2CallStream.emit (events.js:187:15)
    at Http2CallStream.endCall (/Users/MY_PROJECT_PATH/node_modules/@grpc/grpc-js/build/src/call-stream.js:63:18)
    at /Users/MY_PROJECT_PATH/node_modules/@grpc/grpc-js/build/src/call-stream.js:295:18
```

**Comment by alexander-fenster** [comment]
It looks like it's a bug in @grpc/grpc-js v0.4.1 that is our dependency. This bad version already got unpublished. Please rm -rf node_modules and re-run npm install, double checking that grep version node_modules/google-gax/node_modules/@grpc/grpc-js/package.json shows v0.4.0 and not v0.4.1. Thanks!
