### ISSUE TITLE
DLP: Check quasi_id types

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/nodejs-dlp#3]
_From @ace-n on October 17, 2017 18:36_

cc @lukesneeringer 

For DLP's [`kAnonymityConfig`](https://cloud.google.com/dlp/docs/reference/rest/v2beta1/dataSource/analyze#KAnonymityConfig) and [`lDiversityConfig`](https://cloud.google.com/dlp/docs/reference/rest/v2beta1/dataSource/analyze#LDiversityConfig), can we check that the `quasiIds` field's sub-objects specify a `columnName` property?

For example, the following is currently (as of #2668) not caught clientside:
```
const badCfg = "kAnonymityConfig": {
 "quasiIds": [
   {
     "shouldBe_columnName": "Name"
   },
   {
     "shouldBe_columnName": "Age"
   }
 ]
}
```

_Copied from original issue: GoogleCloudPlatform/google-cloud-node#2678_

**Comment by lukesneeringer** [comment]
_From @landrito on October 17, 2017 18:47_

So one way we could do this is to add a check to all request objects to make sure that there are no fields that do not conform to the schema provided in the proto.  I'd have to look at what that would mean for streaming calls though.

@lukesneeringer do you think it's reasonable to add this validation step before shooting off a request?

**Comment by lukesneeringer** [comment]
Probably not. We _consistently_ get bitten when we do client-side validation.

**Comment by stephenplusplus** [comment]
@lukesneeringer it sounds like @landrito tried to make your solution more robust by automating it against the proto. It seems reasonable, assuming it's possible to only return an error if a required argument is not provided. Otherwise, we're making one-off cases here and there, probably too late for the people who would have appreciated the error.

Apologies if I misunderstood any details.

**Comment by realjordanna** [comment]
This validation is done server side and the client should not be doing it.

**Comment by JustinBeckwith** [comment]
@realjordanna does that mean we should close this feature request then?

**Comment by realjordanna** [comment]
Yes, please do @JustinBeckwith  ( i still lack the permissions to do so)
