### ISSUE TITLE
two redact samples tests fail

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/nodejs-dlp#41]
Hi Ace,

The following two tests started failing (possibly flaky). It affects both master commits and nightly runs. Could you please take a look and fix them? Thanks!

  ✖ redact › should redact multiple sensitive data types from an image 
  ✖ redact › should redact a single sensitive data type from an image

**Comment by alexander-fenster** [comment]
Failure: https://circleci.com/gh/googleapis/nodejs-dlp/1438

**Comment by ace-n** [comment]
Naive guess: we need to update the "correct" images to match whatever the API is returning. @crwilcox can you take a look?

**Comment by crwilcox** [comment]
@ace-n I figured that out the long way round :) Added you to PR.
