### ISSUE TITLE
Can't run samples

### ISSUE THREAD

**Issue by kjin** [googleapis/nodejs-dlp#44]
I'm getting this error while running sample code:

```
Cloud Data Loss Prevention (DLP) API has not been used in project 764086051850 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/dlp.googleapis.com/overview?project=764086051850 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```

The DLP API is enabled in my project, and I'm logged in locally. I'm confused because 764086051850 is not my project ID or number, and the link takes me to a page that just gives me an error.

A search on GitHub shows that this so-called "project number" seems to occur pretty often in application-default credentials:

https://github.com/search?q=764086051850&type=Code

#### Environment details

  - OS: macOS 10.13
  - Node.js version: 9
  - npm version: 8.9.3
  - `@google-cloud/dlp` version: 0.2.0

#### Steps to reproduce

  1. Run the sample code: `node redact.js image resources/test.png redaction_result.png -t US_MALE_NAME`

**Comment by alexander-fenster** [comment]
As discussed locally - the `GOOGLE_APPLICATION_CREDENTIALS` environment variable should point to a service account JSON key for the correct project. The application default credentials won't work for DLP.
