### ISSUE TITLE
investigate nightly and sample test failures

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/nodejs-dlp#52]
Samples tests started failing in a weird way https://circleci.com/gh/googleapis/nodejs-dlp/1929 after we changed `--no-timeouts` to `--timeout 600000`. Need to take a look and fix.

**Comment by alexander-fenster** [comment]
It's actually not related to the timeout as the timeout was set for system tests and it's samples test that hang. It's the `inspect.test.js` that fails due to timeout, I can repro locally and looking.

**Comment by alexander-fenster** [comment]
[assigning to @crwilcox, cc: @JustinBeckwith]

Hi Chris,

@ace-n told me you might be the person responsible for these samples.

So basically, all inspect tests (`samples/system-tests/inspect.test.js`) that work with external storage (GCS, Datastore, BigQuery) started failing in nightly and I can easily reproduce those fails locally using our project, `long-door-651`.

Could you please do the following:
- verify that the samples tests timeout (or not) using your DPE project, e.g. the one @ace-n used when he was working on the tests;
- fix the tests so that they don't fail with our project :)

Since it's a nightly failure, I would ask you to prioritize this issue, and if the reason cannot be found quick enough, let's just skip those inspect tests to make sure we have a green run while the problem is being investigated and fixed.

Thanks!

**Comment by alexander-fenster** [comment]
To add to the above: there are no running or pending DLP jobs, it looks like nothing is happening in DLP while the test is being executed. I check using this command:
```sh
export GOOGLE_APPLICATION_CREDENTIALS=/path/to/key  # use your JSON key
export GCLOUD_PROJECT=long-door-651  # use your project name
node jobs.js list ''  | grep -v DONE | grep -v CANCELED
```

**Comment by JustinBeckwith** [comment]
In situations like this I like to:
1. Submit a PR to skip the failing test 
2. File a P1 to come back and fix the issue, ideally within a week.

@alexander-fenster @crwilcox thoughts?

**Comment by alexander-fenster** [comment]
I'm fine with that (in hope that the issue will not be forgotten forever :) )
Marking tests as skipped in #53.

**Comment by kinwa91** [comment]
The tests are complaining about a missing BigQuery dataset resource on our node project.

> Error in kAnonymityAnalysis: 5 NOT_FOUND: BigQuery Dataset: `long-door-651:integration_tests_dlp` not found. If you believe this is incorrect, it is possible that BigQuery is currently experiencing issues, and the problem may be resolved by retrying.

Is that a fixture that we have long-door-651 and has since gone missing?

**Comment by ace-n** [comment]
That table was deleted for some reason. (Data expiry perhaps?)

I added it back just now - run the tests again and see if they pass?

**Comment by realjordanna** [comment]
Check audit log history as to who deleted it?

**Comment by ace-n** [comment]
I did - it was a service account 😔

In any case, it was a) last November and b) likely accidental.

**Comment by ace-n** [comment]
**Update:** there's a [buggy test](https://github.com/googleapis/nodejs-bigquery/blob/master/system-test/bigquery.ts#L1677) that _appears_ to be deleting _all_ datasets in the project, including `integration_tests_dlp`.

@kinwa91 can you investigate?

**Comment by kinwa91** [comment]
@ace-n We just landed a PR to fix nodejs-bigquery to not delete other project's datasets. However I think the dataset was deleted again since you last added it. Can you upload it again?

**Comment by kinwa91** [comment]
ping @ace-n

**Comment by ace-n** [comment]
Recreated the dataset. Try again?

**Comment by JustinBeckwith** [comment]
They look to be fixed 🎉
