### ISSUE TITLE
Support JSON Format 

### ISSUE THREAD

**Issue by madefortv** [googleapis/nodejs-dlp#521]
Thanks for this killer feature! It has been a blast working through the documentation and this may not be the right place to file this feature request. If that is the case please direct me to the correct place! Here goes:

 **Is your feature request related to a problem? Please describe.**
I have had success passing JSON directly to the identification API. Now I would like to redact those findings and *hopefully* get a correctly formatted JSON in response with the redacted InfoTypes. As of right now I am getting the following error
```
Error in deidentifyContent: 3 INVALID_ARGUMENT: `BytesType.BYTES_TYPE_UNSPECIFIED` is not supported for use with de-identification.
``` 
And after some digging I realized this is not supported as a file type yet, When I use the TEXT_UTF8 type, I get a response but the JSON is all garbled and it has proven difficult to remedy this.

 **Describe the solution you'd like**
    1. Add 'JSON' to the enum specified in [dlp.proto](https://github.com/googleapis/nodejs-dlp/blob/62e1b645d48f8ac6e5c09da4a45eae2fb5fc7a76/protos/google/privacy/dlp/v2/dlp.proto#L784)  -> ByteContentItem -> ByteType
    2. Support de-identification for content that is encoded as JSON and outputs a properly formatted JSON blob with the values (and possibly even keys) replaced by the specified de-identification function.

**input.json**
```
{
    "card": "8675-3099-1234-5678",
    "shop": "ZMart"
}
```
Output:
**response.item.value:**
```
{
    "card": "[CREDIT CARD]",
    "shop": "ZMart"
}
```

 **Describe alternatives you've considered**
I have considered biting the bullet and parsing the TEXT_UTF8 string as json.
I have considered doing the redaction key by key or converting the JSON to tabular data before the request and transforming it back after the request

 **Additional context**
Not much

Thanks!

**Comment by sofisl** [comment]
Hi @madefortv, since this library is autogenerated, I think it would be best to submit this feature request directly to the API itself [here](https://issuetracker.google.com/issues/new?component=190846&template=1163023). Thank you!
